In [1]:
from pandas import Series

# create 

In [2]:
a = [1, 2, 3, 4]
s = Series(a)

In [3]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
s.values

array([1, 2, 3, 4])

In [6]:
s1 = Series(a, index=['A','B','C','D'])

In [7]:
s1

A    1
B    2
C    3
D    4
dtype: int64

In [8]:
s1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [9]:
import numpy as np

In [10]:
s2 = Series(np.arange(5))

In [11]:
s2

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [12]:
s2.values

array([0, 1, 2, 3, 4])

In [13]:
d = {'A':1,'B':2,'C':3,'D':4}
s3 = Series(d)

In [14]:
s3

A    1
B    2
C    3
D    4
dtype: int64

In [15]:
s3.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
s3.values

array([1, 2, 3, 4])

In [17]:
s3

A    1
B    2
C    3
D    4
dtype: int64

In [18]:
s3.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [19]:
s3

A    1
B    2
C    3
D    4
dtype: int64

In [20]:
s3['A']

1

In [21]:
s3[s3>2]

C    3
D    4
dtype: int64

In [22]:
type(s3[s3>2])

pandas.core.series.Series

In [23]:
s3.max()

4

In [24]:
s3.min()

1

In [26]:
s3.pop('A')

1

In [28]:
b = s3.pop('B')

In [29]:
s3

C    3
D    4
dtype: int64

In [30]:
b

2

In [31]:
s3

C    3
D    4
dtype: int64

In [32]:
s4 = Series(s3, index=['B','C','D'])

In [33]:
s4

B    NaN
C    3.0
D    4.0
dtype: float64

In [34]:
s4.isnull()

B     True
C    False
D    False
dtype: bool

In [35]:
s4.notnull()

B    False
C     True
D     True
dtype: bool

In [36]:
s4

B    NaN
C    3.0
D    4.0
dtype: float64

In [37]:
s5 = Series(s4, index=['C','D'])

In [38]:
s5

C    3.0
D    4.0
dtype: float64